[config]

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock-colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/kitty-colors.conf'

[templates.librewolf]
input_path = '~/.config/matugen/templates/librewolf.css'
output_path = '~/.config/librewolf/chrome/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = "pkill -SIGUSR2 swaync"

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"

[templates.wleave]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wleave/colors.css'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim-base24.lua'
output_path = '~/.config/nvim/lua/tinted-nvim/palettes/base24-matugen.lua'
post_hook = "pkill -SIGUSR1 nvim || true"

