# Matugen generated hyprlock colors
$bg = rgb(40, 40, 40)
$time = rgb(69, 133, 136)
$username = rgb(215, 153, 33)
$field_outer = rgb(152, 151, 26)
$field_inner = rgb(40, 40, 40)
$capslock = rgb(204, 36, 29)
$font = rgb(235, 219, 178)
