$iDIR="$HOME/.config/swaync/images/ja.png"

general {
    lock_cmd = pidof hyprlock || hyprlock # runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called) 
    before_sleep_cmd = loginctl lock-session # ensures that the session is locked before going to sleep
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # turn off screen after sleep (not strictly necessary, but just in case)
    ignore_dbus_inhibit = false # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

# Warn
listener {
    timeout = 540 # 9 min
    on-timeout = notify-send "idle -- will lock in a minute"
    on-resume = pkill -u $USER notify-send
}

# screen lock
listener {
    timeout = 600 # 10 min
    on-timeout = loginctl lock-session
}

# monitor off 
listener {
    timeout = 840 # 14 min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# suspend
listener {
    timeout = 900 # 15 min
    on-timeout = systemctl suspend
}

