wallpaper {
    monitor = DP-3
    path = ~/Pictures/wallpapers/.current_wallpaper
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/.current_wallpaper
}

#wallpaper=HDMI-A-1 is what second one was before i swapped monitors

splash=false
ipc = on
