# see here for variables https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

general {
    fractional_scaling = 2
    immediate_render = true
}

animations {
    enabled = false
}

background {
    path = ~/Pictures/wallpapers/gruvbox_astronaut.png
    color = rgb(40,40,40) # color will be rendered initially until path is available

    blur_passes = 2
    blur_size = 3
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Date
label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"   # 24h option
    color = rgb(69,133,136)
    font_size = 173
    font_family = Iosevka Term Extrabold
    position = 0, -133
    halign = center
    valign = top
}

# USER
label {
    text =   $USER
    color = rgb(215,153,33)
    font_size = 48
    font_family = Iosevka Term Bold
    position = 0, 250
    halign = center
    valign = bottom
}

# INPUT FIELD
input-field {
    size = 306, 93
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgb(152,151,26)
    inner_color = rgb(40,40,40)
    capslock_color = rgb(204,36,29)
    font_color = rgb(235,219,178)
    fade_on_empty = false
    font_family = Iosevka Term Bold Oblique
    placeholder_text = <i><span foreground="##ffffff99">password</span></i>
    hide_input = false
    position = 0, 100
    halign = center
    valign = bottom
}

