-- matugen template -> tinted-nvim palette module.
-- Renders to: ~/.config/nvim/lua/tinted-nvim/palettes/base24-matugen.lua
-- tinted-nvim resolves custom schemes via require("tinted-nvim.palettes.<name>"),
-- and your ~/.config/nvim shadows the plugin's bundled palettes on runtimepath.
-- Requires the theme JSON (e.g. gruvbox.json) to define all base00..base17 slots
-- plus a "scheme_variant" key ("dark" or "light").
-- Generated by matugen - do not edit.
return {
  variant = "dark",
  base00 = "#282828",
  base01 = "#3c3836",
  base02 = "#504945",
  base03 = "#665c54",
  base04 = "#928374",
  base05 = "#ebdbb2",
  base06 = "#fbf1c7",
  base07 = "#f9f5d7",
  base08 = "#cc241d",
  base09 = "#d65d0e",
  base0A = "#d79921",
  base0B = "#98971a",
  base0C = "#689d6a",
  base0D = "#458588",
  base0E = "#b16286",
  base0F = "#9d0006",
  base10 = "#2a2520",
  base11 = "#1d1d1d",
  base12 = "#fb4934",
  base13 = "#fabd2f",
  base14 = "#b8bb26",
  base15 = "#8ec07c",
  base16 = "#83a598",
  base17 = "#d3869b",
}