# Matugen generated hyprlock colors
$bg = {{ base16.base00.default.rgb }}
$time = {{ base16.base0d.default.rgb }}
$username = {{ base16.base0a.default.rgb }}
$field_outer = {{ base16.base0b.default.rgb }}
$field_inner = {{ base16.base00.default.rgb }}
$capslock = {{ base16.base08.default.rgb }}
$font = {{ base16.base05.default.rgb }}
