background {{ base16.base00.default.hex }}
foreground {{ base16.base05.default.hex }}


cursor {{ base16.base04.default.hex }}

selection_foreground {{ base16.base04.default.hex }}
selection_background {{ base16.base01.default.hex }}

color0 {{ base16.base00.default.hex }}
color8 {{ base16.base04.default.hex }}

# red
color1 {{ base16.base08.default.hex }}
# light red
color9 {{ base16.base12.default.hex }}

# green
color2 {{ base16.base0b.default.hex }}
# light green
color10 {{ base16.base14.default.hex }}

# yellow
color3 {{ base16.base0a.default.hex }}
# light yellow
color11 {{ base16.base13.default.hex }}

# blue
color4 {{ base16.base0d.default.hex }}
# light blue
color12 {{ base16.base16.default.hex }}

# magenta
color5 {{ base16.base0e.default.hex }}
# light magenta
color13 {{ base16.base17.default.hex }}

# cyan
color6 {{ base16.base0c.default.hex }}
# lighy cyan
color14 {{ base16.base15.default.hex }}

# light gray
color7 {{ base16.base03.default.hex }}
# dark gray
color15 {{ base16.base04.default.hex }}

