-- matugen template -> tinted-nvim palette module.
-- Renders to: ~/.config/nvim/lua/tinted-nvim/palettes/base24-matugen.lua
-- tinted-nvim resolves custom schemes via require("tinted-nvim.palettes.<name>"),
-- and your ~/.config/nvim shadows the plugin's bundled palettes on runtimepath.
-- Requires the theme JSON (e.g. gruvbox.json) to define all base00..base17 slots
-- plus a "scheme_variant" key ("dark" or "light").
-- Generated by matugen - do not edit.
return {
  variant = "{{ scheme_variant }}",
  base00 = "{{ base16.base00.default.hex }}",
  base01 = "{{ base16.base01.default.hex }}",
  base02 = "{{ base16.base02.default.hex }}",
  base03 = "{{ base16.base03.default.hex }}",
  base04 = "{{ base16.base04.default.hex }}",
  base05 = "{{ base16.base05.default.hex }}",
  base06 = "{{ base16.base06.default.hex }}",
  base07 = "{{ base16.base07.default.hex }}",
  base08 = "{{ base16.base08.default.hex }}",
  base09 = "{{ base16.base09.default.hex }}",
  base0A = "{{ base16.base0a.default.hex }}",
  base0B = "{{ base16.base0b.default.hex }}",
  base0C = "{{ base16.base0c.default.hex }}",
  base0D = "{{ base16.base0d.default.hex }}",
  base0E = "{{ base16.base0e.default.hex }}",
  base0F = "{{ base16.base0f.default.hex }}",
  base10 = "{{ base16.base10.default.hex }}",
  base11 = "{{ base16.base11.default.hex }}",
  base12 = "{{ base16.base12.default.hex }}",
  base13 = "{{ base16.base13.default.hex }}",
  base14 = "{{ base16.base14.default.hex }}",
  base15 = "{{ base16.base15.default.hex }}",
  base16 = "{{ base16.base16.default.hex }}",
  base17 = "{{ base16.base17.default.hex }}",
}